### ISSUE TITLE
无法手动取消sapi。

### ISSUE THREAD

**Issue by HGWAYEN** [xiaour/spring.boot.sapi.starter#12]
使用sapi后，如果手动注释掉启动类中的@Sapi(controllers = {"com.**.**.controller"})，会报空指针的异常。
报错信息如下（部分）：
java.lang.NullPointerException: null。
at com.github.xiaour.api_scanner.config.SapiFactoryAutoConfigure.registerBeanDefinitions(SapiFactoryAutoConfigure.java:88) ~[xiaour.springboot.sapi.starter-1.4.jar:na]
	at org.springframework.context.annotation.ImportBeanDefinitionRegistrar.registerBeanDefinitions(ImportBeanDefinitionRegistrar.java:86) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:396) ~[spring-context-5.3.18.jar:5.3.18]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[na:1.8.0_202]

目前解决方法：注释@Sapi的同时，删除pom文件中的maven依赖。

**Comment by xiaour** [comment]
后面重新设计开关的方式，不注入也可以
